### ISSUE TITLE
Incorporating Small Molecules

### ISSUE THREAD

**Issue by CoryKornowicz** [tristanic/isolde#4]
Over the past few years, people have slowly been figuring out how to combine small molecules with protein complexes in an efficient and understandable manner. The pipeline is always something following: 
Amber: 
 - using tleap and parmchk to parameterize the molecule in question

OpenFF:
 - using smirnoff or gaff 2.1 to generate the parameters, then combine the molecule with the protein into a complex of forces for OpenMM

How hard would the implementation be to include an option to load or parse an already included small ligand into the local simulation environment? I think this could be game changing for local binding site refinement.

**Comment by CoryKornowicz** [comment]
I did a little digging and figured out how to make it work! I understand now about generating parameters for unknown residues (including small molecules if we pretend they are residues and match the name of the generated parameters file). 

Below I will include a little code snippet I use to make such parameters. 

**Imports**

`from simtk.openmm.app import PDBFile`
`from openff.toolkit.topology import Molecule`
`from openmmforcefields.generators import GAFFTemplateGenerator`
`from rdkit import Chem`

**Small Molecule Preparation**

`rdmol = Chem.MolFromMol2File("{mol2 file here}")`

`Chem.AddHs(rdmol)`
`Chem.AssignAtomChiralTagsFromStructure(rdmol)`
`Chem.AssignStereochemistryFrom3D(rdmol)`

`molecule = Molecule.from_rdkit(rdmol)`

**Parameterizing Ligand**

`gaff = GAFFTemplateGenerator(molecules=molecule)`

`ret = gaff.generate_residue_template(molecule)`
`print(ret)`

This ret is a string of the xml file contents.

**Comment by tristanic** [comment]
Thank you for this, and sorry for being really slow to respond! Incorporating ligand parameterisation via OpenForceField has been on my to-do list for a while now - but a seemingly never-ending series of more immediate, smaller tasks keeps stealing my attention. Just in case you haven't noticed it, ISOLDE's Sim settings tab has a button marked "Load residue MD definition(s)" - load in your XML file through that and your ligand should "just work" in simulations for the remainder of the session. Some caveats:

- the residue name in the model *must* match the name in the template (this differs from standard OpenMM practice because ISOLDE's set of built-in ligand templates includes a number of chiral enantiomers - this breaks OpenMM's topology-matching template selection code because it isn't chirality-aware). Atom names don't have to match (but of course having them match is a good idea for many other reasons).
- If the ligand is still not automatically recognised, chances are the hydrogens are wrong. If your ligand exists in the Chemical Components Dictionary (CCD) and is correctly named, you'll be able to use the Unparameterised residues widget to fix it - it'll fill in all atoms to match the CCD definition, then if necessary adjust the hydrogens to match the MD template. If it's *not* in the CCD, I'm afraid right now you'll need to inspect and correct the hydrogens manually (the ability to add user coordinate templates is still a work in progress). You can do this in ChimeraX: ctrl-click an atom in the ligand, press up once to select the whole ligand, type "show sel" to show all its hydrogens. If you need to delete one, ctrl-click it and "del sel". To add one, ctrl-click the heavy atom to attach it to, then go to ISOLDE/Model Building/Add Hydrogen on the menu.
